########################################
# LZMA C SDK Linux Github Action       #
########################################

name: Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        c: [clang, gcc-10]
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Build LZMA C SDK
    - name: Build LZMA C SDK
      run: |
        cmake -S. -Bbuild -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} --install-prefix ${GITHUB_WORKSPACE}/install
        cmake --build build
        cmake --install build
