#############################################
# LZMA C SDK Windows MSVC2019 Github Action #
#############################################

name: Windows MSVC2019

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install MSYS2
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        release: false
        install: git parallel p7zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-polly mingw-w64-x86_64-mlir mingw-w64-x86_64-clang mingw-w64-x86_64-clang-analyzer mingw-w64-x86_64-clang-tools-extra patch

    # Build LZMA C SDK
    - name: Build LZMA C SDK
      run: |
        cmake -S. -Bbuild  -G "Visual Studio 16 2019"
        cmake --build build
        cmake --install build          