#############################################
# LZMA C SDK Windows MSVC2019 Github Action #
#############################################

name: Windows MSVC2019

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Build LZMA C SDK
    - name: Build LZMA C SDK
      run: |
        cmake . -G "Visual Studio 16 2019"
        cmake --build .
        cmake --install .            